build:
  maxIssues: 0

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 140
  WildcardImport:
    active: true

complexity:
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
  LongMethod:
    threshold: 120
  TooManyFunctions:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
